Delete artisan
CapStoneError404/AmazonHandMade pull request #14
Opened 2019-02-03 23:14 UTC by smrizzo

Abineet and myself pair programmed delete button.
Things added:
1) Delete button in artisan detail (very basic for now)
2) Added Confirm component for confirmation before deleting
3) Added appropriate action to handle the delete button firebase
* For action there was an issue. When delete button was pressed, it deleted correctly from firebase but it would navigate to the artisan list page and fetch from database before the artisan was deleted. So we had to add the code from fetch artisan action in order so that the most recent update to firebase was fetched and dispatched before navigating. There is probably a better way I am sure but for now that was how we did it.

2019-02-04 23:27 UTC, ianbattin requested changes
Looks pretty good, just two comments.

Using the React Native "Alert" (https://facebook.github.io/react-native/docs/alert) would achieve the same thing as your Confirm component but have a native feel for both iOS and Android - I'd recommend using that instead.

For the action, I think you should create a DELETE_ARTISAN reducer and pass the dispatch the artisan which was just deleted. Then in your reducer you can return state - deletedArtisan essentially. Your action code will be simplified and remove unnecessary firebase requests. This might fix your issue with the list not updating as well. You shouldnt need to call the fetch artisans code, you should already have the most up to date list, youre just removing one artisan and so you know what the list should look like afterwards without having to re fetch from firebase.

Also use AsyncButton instead of Button for the delete

2019-02-04 23:34 UTC, ianbattin reviewed
Also it is probably a good idea to add a test which deletes the artisan the Add Artisan test creates - if that exists

2019-02-05 01:09 UTC, smrizzo commented
> Looks pretty good, just two comments.
> 
> Using the React Native "Alert" (https://facebook.github.io/react-native/docs/alert) would achieve the same thing as your Confirm component but have a native feel for both iOS and Android - I'd recommend using that instead.
> 
> For the action, I think you should create a DELETE_ARTISAN reducer and pass the dispatch the artisan which was just deleted. Then in your reducer you can return state - deletedArtisan essentially. Your action code will be simplified and remove unnecessary firebase requests. This might fix your issue with the list not updating as well. You shouldnt need to call the fetch artisans code, you should already have the most up to date list, youre just removing one artisan and so you know what the list should look like afterwards without having to re fetch from firebase.
> 
> Also use AsyncButton instead of Button for the delete

Okay thank you. Yeah your right the alert does look good and more native. I will go ahead and work on that then along with hooking it up with a reducer.

Writing a test is also a good idea. So will go ahead and add that in there.

2019-02-05 22:38 UTC, ianbattin approved these changes

2019-02-05 22:47 UTC, merged