Add detox test
CapStoneError404/AmazonHandMade pull request #9
Opened 2019-01-22 22:26 UTC by smrizzo

### Detox
[Detox Documentation](https://github.com/wix/Detox/blob/master/docs/README.md)
1) Added some login UI testing in a folder named e2e/firstTest.spec.js.
2) This is an example of the structure of creating these UI test.
3) In order to make these test work in that file, need to add testID="" into the props of the specific component on the screen you are testing.
4) Detox only works with react-native components, it will not work with custom made components and a lot of others. 
5) In order to make this work need to pass props down to a component that is from the react-native library. 

### IOS build only right now
1) Clone our project 
2) `npm install`
3) `brew tap wix/brew`
4) `brew install applesimutils`
5) `npm install -g detox-cli`
6) `detox build --configuration ios.sim.debug`
 * If react native packager does not open up then `npm start`
7) `detox test --configuration ios.sim.debug`

This should build your app as if your building it when you type in `react-native run-ios`
Then then after running detox test--configuration ios.sim.debug it will run the test I currently have

2019-01-23 23:28 UTC, ianbattin requested changes

2019-01-23 23:28 UTC, ianbattin commented on AmazonHandmadeRN/src/App.js
> +{/* <TouchableOpacity testID='greetings' onPress={() => this.setState({ greetings: 'new text now' })}>
Unless this is going to be uncommented in a future commit, delete it for now

2019-01-23 23:28 UTC, ianbattin commented on AmazonHandmadeRN/src/screens/ArtisanHub/ArtisanList.js
> +     console.log(`listItem${index}`);
Remove unnecessary console logs

2019-01-24 17:28 UTC, smrizzo commented on AmazonHandmadeRN/src/App.js
> +{/* <TouchableOpacity testID='greetings' onPress={() => this.setState({ greetings: 'new text now' })}>
Okay will remove that then.

2019-01-24 17:29 UTC, smrizzo commented on AmazonHandmadeRN/src/screens/ArtisanHub/ArtisanList.js
> +     console.log(`listItem${index}`);
Also will remove console log, and be sure to remove those before PR.

2019-01-24 20:30 UTC, ianbattin requested changes

2019-01-24 20:30 UTC, ianbattin commented on e2e/init.js
> +// const detox = require('detox');
Is there a reason all this commented out code is here?

2019-01-24 20:30 UTC, ianbattin commented on src/App.js
> +{/* <TouchableOpacity testID='greetings' onPress={() => this.setState({ greetings: 'new text now' })}>
Delete this

2019-01-24 20:30 UTC, ianbattin commented on src/screens/ArtisanHub/ArtisanList.js
> +     console.log(`listItem${index}`);
Delete this

2019-01-24 22:29 UTC, smrizzo commented on e2e/init.js
> +// const detox = require('detox');
No should be gone now

2019-01-24 22:29 UTC, smrizzo commented on src/App.js
> +{/* <TouchableOpacity testID='greetings' onPress={() => this.setState({ greetings: 'new text now' })}>
Yep deleted

2019-01-24 22:29 UTC, smrizzo commented on src/screens/ArtisanHub/ArtisanList.js
> +     console.log(`listItem${index}`);
Deleted

2019-01-24 22:30 UTC, ianbattin requested changes

2019-01-24 22:30 UTC, ianbattin commented on e2e/artisanDetail.spec.js
> +    await element(by.id('email_login')).replaceText('user@user.com');
Indentation should be 2 spaces not 1

2019-01-24 22:30 UTC, ianbattin commented on e2e/artisanDetail.spec.js
> +   await expect(element(by.text('Settings'))).toBeVisible();
2 spaces

2019-01-24 22:30 UTC, ianbattin commented on e2e/firstTest.spec.js
> +   await expect(element(by.id('handmade_logo'))).toBeVisible();
2 spaces needed

2019-01-24 22:35 UTC, ianbattin requested changes
Also can you add a section to the README containing your instructions which you have in the PRs comment?

2019-01-24 22:40 UTC, smrizzo commented
> Also can you add a section to the README containing your instructions which you have in the PRs comment?

2019-01-24 22:41 UTC, smrizzo commented
> Also can you add a section to the README containing your instructions which you have in the PRs comment?

Yeah I can start that after start the code review

2019-01-24 22:44 UTC, ianbattin commented
> > Also can you add a section to the README containing your instructions which you have in the PRs comment?
> 
> Yeah I can start that after start the code review

You can just edit the README contained it your branch, that way those changes become a part of this PR, not sure if thats what you meant

2019-01-24 22:53 UTC, smrizzo commented
> > > Also can you add a section to the README containing your instructions which you have in the PRs comment?
> > 
> > 
> > Yeah I can start that after start the code review
> 
> You can just edit the README contained in this branch, that way those changes become a part of this PR, not sure if thats what you meant

2019-01-24 23:16 UTC, ianbattin approved these changes
Also can you add a section to the README containing your instructions which you have in the PRs comment?

2019-01-24 23:38 UTC, merged